"""add paiement_tranche table

Revision ID: 69b8ba381a6d
Revises: 30dcbacb1fd4
Create Date: 2026-09-09 11:41:48.280959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69b8ba381a6d'
down_revision = '30dcbacb1fd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paiement_tranche',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paiement_id', sa.Integer(), nullable=False),
    sa.Column('tranche_paiement_id', sa.Integer(), nullable=False),
    sa.Column('montant_affecte', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('montant_affecte > 0', name='ck_paiement_tranche_montant_positif'),
    sa.ForeignKeyConstraint(['paiement_id'], ['paiement.id'], ),
    sa.ForeignKeyConstraint(['tranche_paiement_id'], ['tranche_paiement.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('paiement_id', 'tranche_paiement_id', name='uq_paiement_tranche')
    )
    with op.batch_alter_table('paiement', schema=None) as batch_op:
        batch_op.drop_column('tranche_paiement_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paiement', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tranche_paiement_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key(None, 'tranche_paiement', ['tranche_paiement_id'], ['id'])

    op.drop_table('paiement_tranche')
    # ### end Alembic commands ###
