"""initial schema

Revision ID: bcccc52c0f57
Revises: 
Create Date: 2026-07-11 12:46:07.287586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcccc52c0f57'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('annee_scolaire',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('libelle', sa.String(length=20), nullable=False),
    sa.Column('date_debut', sa.Date(), nullable=True),
    sa.Column('date_fin', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('libelle', name='uq_annee_libelle')
    )
    op.create_table('creneau_horaire',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('libelle', sa.String(length=50), nullable=False),
    sa.Column('heure_debut', sa.Time(), nullable=False),
    sa.Column('heure_fin', sa.Time(), nullable=False),
    sa.Column('ordre', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ordre')
    )
    op.create_table('cycle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ordre', sa.Integer(), nullable=False),
    sa.Column('libelle', sa.String(length=50), nullable=False),
    sa.Column('cycle', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('enseignant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('prenom', sa.String(length=100), nullable=False),
    sa.Column('telephone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('grade', sa.String(length=50), nullable=True),
    sa.Column('est_titulaire', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('etablissement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=150), nullable=False),
    sa.Column('nom_bilingue', sa.String(length=150), nullable=True),
    sa.Column('adresse', sa.String(length=255), nullable=True),
    sa.Column('bp', sa.String(length=50), nullable=True),
    sa.Column('telephone', sa.String(length=20), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('logo_url', sa.String(length=255), nullable=True),
    sa.Column('code_acces_hash', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('groupe_matiere',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('libelle', sa.String(length=150), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('prenom', sa.String(length=100), nullable=False),
    sa.Column('telephone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('adresse', sa.String(length=255), nullable=True),
    sa.Column('profession', sa.String(length=150), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('classe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cycle_id', sa.Integer(), nullable=False),
    sa.Column('effectif', sa.Integer(), nullable=True),
    sa.Column('option', sa.String(length=50), nullable=True),
    sa.Column('salle', sa.String(length=30), nullable=True),
    sa.Column('libelle', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['cycle_id'], ['cycle.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('eleve',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('matricule', sa.String(length=30), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('prenom', sa.String(length=100), nullable=False),
    sa.Column('date_naissance', sa.Date(), nullable=True),
    sa.Column('lieu_naissance', sa.String(length=150), nullable=True),
    sa.Column('sexe', sa.String(length=1), nullable=True),
    sa.Column('adresse', sa.String(length=255), nullable=True),
    sa.Column('photo_url', sa.String(length=255), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("sexe IN ('M', 'F')", name='ck_eleve_sexe'),
    sa.ForeignKeyConstraint(['parent_id'], ['parent.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('matricule')
    )
    op.create_table('matiere',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('libelle', sa.String(length=150), nullable=False),
    sa.Column('groupe_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['groupe_id'], ['groupe_matiere.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('libelle', 'groupe_id', name='uq_matiere_groupe')
    )
    op.create_table('tranche_paiement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('annee_scolaire_id', sa.Integer(), nullable=False),
    sa.Column('libelle', sa.String(length=100), nullable=False),
    sa.Column('montant_attendu', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('date_limite', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('montant_attendu > 0', name='ck_tranche_montant_positif'),
    sa.ForeignKeyConstraint(['annee_scolaire_id'], ['annee_scolaire.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trimestre',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('annee_scolaire_id', sa.Integer(), nullable=False),
    sa.Column('libelle', sa.String(length=20), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('date_debut', sa.Date(), nullable=True),
    sa.Column('date_fin', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['annee_scolaire_id'], ['annee_scolaire.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('annee_scolaire_id', 'numero', name='uq_trimestre_annee_numero')
    )
    op.create_table('inscription',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('eleve_id', sa.Integer(), nullable=False),
    sa.Column('classe_id', sa.Integer(), nullable=False),
    sa.Column('annee_scolaire_id', sa.Integer(), nullable=False),
    sa.Column('date_inscription', sa.Date(), nullable=True),
    sa.Column('statut', sa.String(length=20), nullable=False),
    sa.Column('redoublant', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("statut IN ('Inscrit', 'Redoublant', 'Transfere', 'Abandon')", name='ck_inscription_statut'),
    sa.ForeignKeyConstraint(['annee_scolaire_id'], ['annee_scolaire.id'], ),
    sa.ForeignKeyConstraint(['classe_id'], ['classe.id'], ),
    sa.ForeignKeyConstraint(['eleve_id'], ['eleve.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('eleve_id', 'annee_scolaire_id', name='uq_inscription_eleve_annee')
    )
    op.create_table('matiere_classe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('classe_id', sa.Integer(), nullable=False),
    sa.Column('matiere_id', sa.Integer(), nullable=False),
    sa.Column('enseignant_id', sa.Integer(), nullable=False),
    sa.Column('coefficient', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['classe_id'], ['classe.id'], ),
    sa.ForeignKeyConstraint(['enseignant_id'], ['enseignant.id'], ),
    sa.ForeignKeyConstraint(['matiere_id'], ['matiere.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('classe_id', 'matiere_id', name='uq_matiere_classe')
    )
    op.create_table('sequence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trimestre_id', sa.Integer(), nullable=False),
    sa.Column('libelle', sa.String(length=10), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('date_debut', sa.Date(), nullable=True),
    sa.Column('date_fin', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['trimestre_id'], ['trimestre.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trimestre_id', 'numero', name='uq_sequence_trimestre_numero')
    )
    op.create_table('titulaire_classe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('classe_id', sa.Integer(), nullable=False),
    sa.Column('enseignant_id', sa.Integer(), nullable=False),
    sa.Column('annee_scolaire_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['annee_scolaire_id'], ['annee_scolaire.id'], ),
    sa.ForeignKeyConstraint(['classe_id'], ['classe.id'], ),
    sa.ForeignKeyConstraint(['enseignant_id'], ['enseignant.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('classe_id', 'annee_scolaire_id', name='uq_titulaire_classe_annee')
    )
    op.create_table('discipline',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inscription_id', sa.Integer(), nullable=False),
    sa.Column('sequence_id', sa.Integer(), nullable=False),
    sa.Column('absences_justifiees', sa.Integer(), nullable=False),
    sa.Column('absences_non_justifiees', sa.Integer(), nullable=False),
    sa.Column('retards', sa.Integer(), nullable=False),
    sa.Column('exclusions', sa.Integer(), nullable=False),
    sa.Column('observation', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['inscription_id'], ['inscription.id'], ),
    sa.ForeignKeyConstraint(['sequence_id'], ['sequence.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('inscription_id', 'sequence_id', name='uq_discipline_inscription_sequence')
    )
    op.create_table('horaire',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('matiere_classe_id', sa.Integer(), nullable=False),
    sa.Column('annee_scolaire_id', sa.Integer(), nullable=False),
    sa.Column('jour_semaine', sa.String(length=10), nullable=False),
    sa.Column('creneau_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("jour_semaine IN ('Lundi', 'Mardi', 'Mercredi', 'Jeudi', 'Vendredi', 'Samedi')", name='ck_horaire_jour'),
    sa.ForeignKeyConstraint(['annee_scolaire_id'], ['annee_scolaire.id'], ),
    sa.ForeignKeyConstraint(['creneau_id'], ['creneau_horaire.id'], ),
    sa.ForeignKeyConstraint(['matiere_classe_id'], ['matiere_classe.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('matiere_classe_id', 'jour_semaine', 'creneau_id', 'annee_scolaire_id', name='uq_horaire_matiere_classe_creneau')
    )
    op.create_table('note',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inscription_id', sa.Integer(), nullable=False),
    sa.Column('matiere_classe_id', sa.Integer(), nullable=False),
    sa.Column('sequence_id', sa.Integer(), nullable=False),
    sa.Column('valeur', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('absent', sa.Boolean(), nullable=False),
    sa.Column('saisie_le', sa.DateTime(), nullable=False),
    sa.CheckConstraint('valeur >= 0 AND valeur <= 20', name='ck_note_valeur_range'),
    sa.ForeignKeyConstraint(['inscription_id'], ['inscription.id'], ),
    sa.ForeignKeyConstraint(['matiere_classe_id'], ['matiere_classe.id'], ),
    sa.ForeignKeyConstraint(['sequence_id'], ['sequence.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('inscription_id', 'matiere_classe_id', 'sequence_id', name='uq_note_inscription_matiere_sequence')
    )
    op.create_table('paiement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inscription_id', sa.Integer(), nullable=False),
    sa.Column('tranche_paiement_id', sa.Integer(), nullable=False),
    sa.Column('montant_verse', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('date_paiement', sa.Date(), nullable=True),
    sa.Column('mode_paiement', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('montant_verse > 0', name='ck_paiement_montant_positif'),
    sa.ForeignKeyConstraint(['inscription_id'], ['inscription.id'], ),
    sa.ForeignKeyConstraint(['tranche_paiement_id'], ['tranche_paiement.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('paiement')
    op.drop_table('note')
    op.drop_table('horaire')
    op.drop_table('discipline')
    op.drop_table('titulaire_classe')
    op.drop_table('sequence')
    op.drop_table('matiere_classe')
    op.drop_table('inscription')
    op.drop_table('trimestre')
    op.drop_table('tranche_paiement')
    op.drop_table('matiere')
    op.drop_table('eleve')
    op.drop_table('classe')
    op.drop_table('parent')
    op.drop_table('groupe_matiere')
    op.drop_table('etablissement')
    op.drop_table('enseignant')
    op.drop_table('cycle')
    op.drop_table('creneau_horaire')
    op.drop_table('annee_scolaire')
    # ### end Alembic commands ###
