"""add license_state

Revision ID: c64dd5054607
Revises: e4e85a4ff90b
Create Date: 2026-09-11 03:46:38.217303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c64dd5054607'
down_revision = 'e4e85a4ff90b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('license_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('license_payload', sa.Text(), nullable=False),
    sa.Column('school_id', sa.String(length=100), nullable=False),
    sa.Column('hwid', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.Integer(), nullable=False),
    sa.Column('activated_at', sa.Integer(), nullable=False),
    sa.Column('last_seen_timestamp', sa.Integer(), nullable=False),
    sa.Column('integrity_hmac', sa.String(length=64), nullable=False),
    sa.CheckConstraint('id = 1', name='ck_license_state_singleton'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('license_state')
    # ### end Alembic commands ###
